### ISSUE TITLE
I think we are using this Github integration wrong.

### ISSUE THREAD

**Issue by Nissenice** [ElComadore/Matematiska-S-ll#1]
We should probably each have our own project in Overleaf that we sync to this Github repository and not be working on the same Overleaf project.

To do this I think you need to add our Github profiles as contributors to the repository.

**Comment by ElComadore** [comment]
While I agree that it might be nicer to all have separate Overleaf projects might it not get a bit too decentralised? Is the point of the github not to act as a version manager?

**Comment by Nissenice** [comment]
Yes that's the point of the github repo, but that isn't working that well right now. Check the last commits to see what I mean.

**Comment by ElComadore** [comment]
You want it so that the commits appear by different authors? I agree that would be nice, but as it stands the history keeping functionality still works. To make it clearer we could always put our names at the start of the commit?
